Formatted phase_angle tool as well as including error classes
QCpython/qcpy pull request #104
Opened 2024-10-27 23:26 UTC by brennanfreeze

# Pull Request

## Description

Please include a summary of the changes and the motivation behind them. If applicable, link to any related issues.

## Type of Change

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Documentation
- [ ] Refactoring
- [ ] Other (please specify): 

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the documentation accordingly.
- [x] I ran `black` formatter on the codebase. (CI/CD will fail if neglected)
- [x] My code follows the project's coding style guidelines.

## Related Issues

- Closes #82 
- Related to #

## Screenshots (if applicable)

If your change includes visual updates, please include screenshots to demonstrate the changes.

## Additional Notes

Add any additional notes or comments here. For example, describe any known issues or limitations.

2024-10-28 23:54 UTC, parisosuch-dev requested changes
I think we are missing the raise of an error here

2024-10-28 23:54 UTC, parisosuch-dev commented on src/tools/phase_angle.py
> +        RoundBelowZero(f"Cannot round to {round} needs to be 0 or greater")
correct me if im wrong but wouldn't you want to do `raise RoundBelowZero()`? Maybe I didn't know you can raise an error in python without explicitly using the keyword `raise`

2024-10-28 23:54 UTC, parisosuch-dev commented on src/tools/phase_angle.py
> +            OutOfRangeError(
Same with this one as well.

2024-10-28 23:54 UTC, parisosuch-dev commented on src/tools/phase_angle.py
> +            OutOfRangeError(
and this one

2024-10-29 02:36 UTC, brennanfreeze commented on src/tools/phase_angle.py
> +            OutOfRangeError(
Thanks for spotting this, updated this!

2024-10-29 03:44 UTC, parisosuch-dev approved these changes
sweet!

2024-10-29 03:47 UTC, merged